# Generated by Django 5.2.17 on 2026-08-22 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(max_length=100)),
                ('modality', models.CharField(choices=[('ONSITE', 'Presencial'), ('HYBRID', 'Híbrido'), ('REMOTE', 'Remoto')], max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
                ('practice', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('IN_PROCESS', 'En proceso'), ('INTERVIEW', 'En entrevistas'), ('CLOSED', 'Cerrada')], default='ACTIVE', max_length=20)),
                ('opening_date', models.DateField()),
                ('requester', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Postulado'), ('REVIEW', 'En revisión'), ('INTERVIEW', 'Entrevista'), ('SELECTED', 'Seleccionado'), ('REJECTED', 'Descartado')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='desafio_api.candidate')),
                ('recruitment_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='desafio_api.recruitmentsearch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'recruitment_search'), name='unique_candidate_search_application')],
            },
        ),
    ]
